apiVersion: skaffold/v2alpha2
kind: Config
metadata:
  name: my-voting-app
build:
  artifacts:
    - image: frontend-image
      context: src/frontend-service
    - image: voting-image
      context: src/voting-service
  tagPolicy:
    sha256: {}
  local:
    useBuildkit: false
    useDockerCLI: false
profiles:
  - build:
    deploy:
      kubectl:
        manifests:
          - kubernetes-manifests/frontend.yml
          - kubernetes-manifests/voting.yml
    name: local
  - build:
      googleCloudBuild:
        projectId: sreemakam-demo
    deploy:
      kubectl:
        manifests:
          - kubernetes-manifests/*.yml
    name: cloud
  - build:
      googleCloudBuild:
        projectId: sreemakam-demo
    deploy:
      kustomize:
        path: ./base-manifest/
    name: base
  - build:
      googleCloudBuild:
        projectId: sreemakam-demo
    deploy:
      kustomize:
        path: ./dev-manifest/
    name: clouddev
  - build:
      googleCloudBuild:
        projectId: sreemakam-demo
    deploy:
      kustomize:
        path: ./prod-manifest/
    name: cloudprod
